#ifndef TEXTS_H
#define TEXTS_H

typedef enum {
    // START MENU
    TXT_WELCOME_TITLE = 0,
    TXT_CREATE_NOTE,
    TXT_VIEW_NOTES,
    TXT_WIFI_CONNECTION,
    TXT_THEME_LABEL,
    TXT_START_INSTRUCTIONS,
    
    // GALLERY
    TXT_BACK_B,
    TXT_NO_NOTES_FOUND,
    TXT_CREATE_NOTE_IN_START_MENU,
    TXT_MORE_NOTES_ABOVE,
    TXT_MORE_NOTES_BELOW,
    TXT_GALLERY_INSTRUCTIONS,
    
    // CONNECTION WIZARD
    TXT_CONN_SETTINGS,
    TXT_CANCEL,
    TXT_SAVE,
    TXT_PAIRING_CONFIG,
    TXT_CODE,
    TXT_ENTER_CODE_1,
    TXT_ENTER_CODE_2,
    TXT_CODIGO_CAPS,
    TXT_EMPTY_SLOT,
    TXT_MANUAL_KEYBOARD,
    
    // TOOLBAR
    TXT_TOOLBAR_PINC,
    TXT_TOOLBAR_BORR,
    TXT_TOOLBAR_ENVIAR,
    
    // SIDEBAR
    TXT_SIDEBAR_CAPAS,
    TXT_SIDEBAR_ADD_CAPA,
    TXT_SIDEBAR_LLENO,
    TXT_SIDEBAR_CAPA,
    TXT_SIDEBAR_FONDO,
    TXT_SIDEBAR_MOD,
    TXT_SIDEBAR_LOK,
    TXT_SIDEBAR_C_ABJ,
    TXT_SIDEBAR_C_ARB,
    
    // MODALS
    TXT_UTENSILIO,
    TXT_PINCEL,
    TXT_BORRADOR,
    TXT_RELLENO,
    TXT_TRAZO,
    TXT_NORMAL,
    TXT_ROTUL,
    TXT_PATRON_BRUSH,
    TXT_PLUMAS,
    TXT_GROSOR_BORRADOR,
    TXT_GROSOR_PINCEL,
    TXT_PRESETS,
    TXT_MIS_PALETAS,
    TXT_GUARDAR_BTN,
    TXT_PATRONES,
    TXT_PERSPECTIVA,
    TXT_MOD_SI,
    TXT_MOD_NO,
    TXT_MODO_PERSPECTIVA,
    TXT_REUBICAR_PUNTOS,
    TXT_SIN_PERSPECTIVA,
    TXT_PUNTO_1,
    TXT_PUNTO_2,
    TXT_PUNTO_3,
    TXT_PUNTO_4,
    TXT_DENSIDAD_REJILLA,
    TXT_ROTACION_FONDO,
    TXT_ANGULO_PLUMA,
    TXT_MENU_NOTA,
    TXT_GUARDAR_NOTA_SD,
    TXT_WIFI_CONEXION_MODAL,
    TXT_VOLVER_AL_MENU_INICIO,
    TXT_CANCELAR_MODAL,
    TXT_GUARDAR_ANTES_DE_SALIR,
    TXT_SI_GUARDAR_Y_SALIR,
    TXT_NO_SALIR_SIN_GUARDAR,
    TXT_SELECCIONAR_IDIOMA,
    TXT_CERRAR,
    
    // UPLOAD FLOW
    TXT_UPLOAD_ENVIANDO,
    TXT_UPLOAD_WIFI_INIT,
    TXT_UPLOAD_WIFI_FAIL,
    TXT_UPLOAD_PNG_ENCODE,
    TXT_UPLOAD_OOM,
    TXT_UPLOAD_CONNECTING,
    TXT_UPLOAD_SUCCESS,
    TXT_UPLOAD_ERROR,
    
    // NEW CODES FOR FRENCH AND KEYBOARD
    TXT_COL_ABBR,
    TXT_SIZE_ABBR_FORMAT,
    TXT_KEY_CANCEL,
    TXT_KEY_SAVE,
    TXT_KEY_SPACE,
    TXT_KEY_LAYER_PROP,
    TXT_BG_ABBR_FORMAT,
    
    TXT_MAX
} TextId;

const char* uiTxt(TextId id);

#endif // TEXTS_H
